font:
  file: "Lord_Nightmare-Fixedsys-03.png"
  width: 8
  height: 16
  row: 16

canvas:
  width: 100
  height: 40

randomizer:
  - - char: 1
      ratio: 0.2
    - char: 2
      ratio: 0.6

  - - char: 3
      ratio: 1
    - char: 4
      ratio: 0.1

shortcut:
  - 1
  - 2

colors:
  - "255,0,0"
  - "0,255,0"
  - "0,0,255"

files:
  save: "./save/project_{slot}.{ext}"
  export: "./export/export_{slot}.{ext}"
  autosave: "./autosave/project_{slot}_{date}.{ext}"
